title: Autonomy Hands and Faces
description: Autonomy Hands and Faces, Robust Real-Time Hands-and-Face Detection for Human Robot Interaction.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker